---
title: "Laboratorio4"
author: "Mafer Pérez"
date: "28 de agosto de 2019"
output: rmarkdown::github_document
---

```{r, cache = TRUE}
library(tidyr)
library(reshape2)
library(dplyr)
library(stringr)
#ejercicio de la clase
df <- data.frame(row= LETTERS[1:3], a= 1:3, b= 4:6, c=7:9)
df
#melt de reshape2
dfm <- melt(df, id= "row")

#gather de Tidyr
dfg <- gather(df, key="variable", value= "value", a:c)
dfg

colnames(dfg) <- c("row", "letras", "valores")
dfg

```

```{r, cache = TRUE}
library(plyr)
library(readr)
raw <- read_csv(file = "raw.csv") %>% select(-X1)
raw$mu <- NULL
raw$fu <- NULL
raw <- gather(raw, key="age", value ="freq" , m014:f65) %>% arrange(country)
#raw <- na.omit(raw)
raw$sexo <- str_sub(raw$age, start = 1, end = 1)
raw$edad <- str_sub(raw$age, start=2)
raw$edad <- revalue(raw$edad, c('014' = "0-14", '1524' = "15-24", '2534' = "25-34", '3544' = "35-44", '4554' = "45-54", '5564' = "55-64", '65' = "65+"))
raw1 <- raw %>% select(country, year, sexo, edad, freq)
head(raw1)
```

```{r, cache = TRUE}
load(file = "wide_religion.rda")
religion <- gather(wide_religion, key="income", value ="freq", '<$10k':"Don't know/refused") %>% arrange(religion)
religion
```

